// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wohfoyadzhuzapgjqxfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvaGZveWFkemh1emFwZ2pxeGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjY5NTcsImV4cCI6MjA2NDY0Mjk1N30.9hxs9pkklkn1G8on35_iYxVouMgShZrFcHSgTTrTqe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);